entity: WhoIsConfig
items:
  whoIsConfig0:
    configType: 'WhoIsConfig'
    gameName: 'Who is'
    phase: '@phase0'
    title: 'Who is'
    cards:
      - '@whoIsCard0'
      - '@whoIsCard1'
  
  whoIsConfig1:
    configType: 'WhoIsConfig'
    gameName: 'Who is'
    phase: '@phase1'
    title: 'Who is'
    cards:
      - '@whoIsCard0'
      - '@whoIsCard1'

  whoIsConfig2:
    configType: 'WhoIsConfig'
    gameName: 'Who is'
    title: 'Who is'
    phase: '@phase2'
    cards:
      - '@whoIsCard0'
      - '@whoIsCard1'
  
  whoIsConfig3:
    configType: 'WhoIsConfig'
    gameName: 'Who is'
    title: 'Who is'
    cards:
      - '@whoIsCard0'
      - '@whoIsCard1'