# Docker compose to simulate production environment
# To run: docker compose -f docker-compose.yml -f docker-compose-production.yml up
version: '3'

services:
  app: 
    container_name: together
    ports: 
      - ${PORT}:${PORT}
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    links: 
        - db