entity: DoubleDiceBoardConfig
items:
  doubleDiceBoardConfig0:
    configType: 'DoubleDiceBoardConfig'
    gameName: 'Double dice board'
    title: 'Double dice board test'
    doubleDiceBoardMinRounds: 2
    doubleDiceBoardTiles:
      - '@doubleDiceBoardTile0'
      - '@doubleDiceBoardTile1'
      - '@doubleDiceBoardTile2'
      - '@doubleDiceBoardTile3'
      - '@doubleDiceBoardTile4'
      - '@doubleDiceBoardTile5'
      - '@doubleDiceBoardTile6'
      - '@doubleDiceBoardTile7'
      - '@doubleDiceBoardTile8'
      - '@doubleDiceBoardTile9'
      - '@doubleDiceBoardTile10'
      - '@doubleDiceBoardTile11'
      - '@doubleDiceBoardTile12'
      - '@doubleDiceBoardTile13'
      - '@doubleDiceBoardTile14'
      - '@doubleDiceBoardTile15'
      - '@doubleDiceBoardTile16'
      - '@doubleDiceBoardTile17'
      - '@doubleDiceBoardTile18'
      - '@doubleDiceBoardTile19'
      - '@doubleDiceBoardTile20'
      - '@doubleDiceBoardTile21'
      - '@doubleDiceBoardTile22'
      - '@doubleDiceBoardTile23'
      - '@doubleDiceBoardTile24'
      - '@doubleDiceBoardTile25'
      - '@doubleDiceBoardTile26'
      - '@doubleDiceBoardTile27'
      - '@doubleDiceBoardTile28'
      - '@doubleDiceBoardTile29'
      - '@doubleDiceBoardTile30'
      - '@doubleDiceBoardTile31'
      - '@doubleDiceBoardTile32'
      - '@doubleDiceBoardTile33'
      - '@doubleDiceBoardTile34'
      - '@doubleDiceBoardTile35'